import 'public/style.css';

export const Separator = () => {
  return (
    <div className="flex items-center">
      <div className="flex-1 h-0.5">
        <div className="animate-gradient w-full h-full"></div>
      </div>
      <div className="px-4">
        <p className="text-center">Companions generated by the community!</p>
      </div>
      <div className="flex-1 h-0.5">
        <div className="animate-gradient w-full h-full"></div>
      </div>
    </div>
  );
};
  